baseURL = "https://UmmeHabiba-7119.github.io/habiba-website/"
languageCode = "en-us"
title = "Umme Habiba"
theme = "PaperMod"

[pagination]
pagerSize = 5

[params]
defaultTheme = "light"
ShowReadingTime = false
ShowShareButtons = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowToc = false

[params.profileMode]
enabled = true
title = "Umme Habiba"
subtitle = """
Lecturer, Department of Computer Science & Engineering

Daffodil International University

Research Interests:
Machine Learning • Deep Learning • Remote Sensing
"""

imageUrl = "/images/profile.jpg"
imageTitle = "Umme Habiba"

[[params.profileMode.buttons]]
name = "Projects"
url = "/projects/"

[[params.profileMode.buttons]]
name = "Research"
url = "/research/"


[[params.profileMode.buttons]]
name = "About"
url = "/about/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/UmmeHabiba-7119"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/YOUR_USERNAME"

[[params.socialIcons]]
name = "email"
url = "mailto:YOUR_EMAIL"

ShowReadingTime = false
ShowBreadCrumbs = false
ShowPostNavLinks = false
ShowShareButtons = false
ShowCodeCopyButtons = false

[params.assets]
disableFingerprinting = false

[params.label]
text = "UH Portfolio"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "education"
name = "Education"
url = "/education/"
weight = 2

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 3

[[menu.main]]
identifier = "research"
name = "Research"
url = "/research/"
weight = 4

[[menu.main]]
identifier = "skills"
name = "Skills"
url = "/skills/"
weight = 5

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 6

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 7

[[params.profileMode.buttons]]
name = "Resume"
url = "/resume"